version: '3'
services:
  nginx_filebeat:
    image: "dm90/pibeats"
    volumes:
    # the filebeat config file
    - ./pibeat_nginx.yml:/filebeat/filebeat.yml
    # the tls cert referenced by the above config file
    - ./logstash-beats.crt:/filebeat/logstash-beats.crt
    # the startup script
    - ./start.sh:/filebeat/start.sh
    # read-only access to the nginx logs on the rpi host
    - /var/log/nginx/:/var/log/nginx:ro
    # read-only access to the hosts file on the host
    # (this is helpful for local netowrk stuff... where I don't have a DNS)
    - /etc/hosts:/etc/hosts:ro
    # For a persistent registry, use a named volume.
    # Otherwise don't use this... logs will entirely re-ship when the container restarts
    - nginx-pibeat:/filebeat/data
    entrypoint:
    # override the entrypoint with custom startup script
    - /filebeat/start.sh
volumes:
  nginx-pibeat: